import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

const FROM = process.env.FROM_EMAIL || 'onboarding@resend.dev';
const FROM_NAME = '戦略大臣';

async function sendEmail(to, subject, html) {
  if (!resend) {
    console.log('📧 [メール送信スキップ] Resend API キー未設定');
    return { success: true, skipped: true };
  }
  try {
    const data = await resend.emails.send({ from: `${FROM_NAME} <${FROM}>`, to: [to], subject, html });
    return { success: true, data };
  } catch (error) {
    console.error('メール送信エラー:', error);
    return { success: false, error };
  }
}

export async function sendRegistrationEmail({ email, name }) {
  return sendEmail(email, '【戦略大臣】ご登録が完了しました', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、ご登録ありがとうございます。</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">戦略大臣は、300万円の事業戦略立案サービスをボタン一つで可能にしたツールです。</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">生成AIに戦略を相談すると都度都度の対処療法的な回答になりがちです。先日はこう言っていたのに今日はこんなふうに言っている——矛盾した回答に戸惑うことがありませんか？</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">戦略大臣では環境調査をした上で戦略を固めることで、その後のマーケティングの軸が定まり、一貫性のある経営戦略の実行が可能になります。</p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0 0 12px">無料トライアルでできること：</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 4px">・AB3C分析レポート：1回</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 4px">・Webサイト改善レポート：1回</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">・AIチャット相談：1回</p></div><p style="font-size:16px;line-height:1.8;color:#1a1a14">あなたのWebサイトのURLを入れてお試しください。</p><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold;margin-top:8px">さっそく分析を始める →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendWelcomeEmail({ email, name }) {
  return sendEmail(email, 'あなたのビジネスの「選ばれる理由」、一緒に見つけましょう。', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、ありがとうございます。自社利用でご登録いただきました。</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">早速ですが、一つ質問させてください。</p><p style="font-size:18px;font-weight:bold;line-height:1.8;color:#1a6fd4;border-left:4px solid #1a6fd4;padding-left:16px;margin:24px 0">「なぜお客様はあなたから買うのですか？」</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">この質問にすぐ答えられる経営者は、実はほとんどいません。でも、この「選ばれる理由」が言語化できた瞬間から、Webサイトも、営業も、採用も、すべてが変わり始めます。</p><hr style="border:none;border-top:1px solid #e5e5e0;margin:32px 0"><p style="font-size:15px;font-weight:bold;color:#1a1a14;margin-bottom:20px">戦略大臣の使い方には2つのフェーズがあります。</p><div style="background:#f0f4ff;border-radius:8px;padding:20px 24px;margin-bottom:16px"><p style="font-size:13px;font-weight:bold;color:#1a6fd4;margin:0 0 8px">① 戦略策定フェーズ</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">AB3C分析で「選ばれる理由」を言語化し、戦略を固めます。分析結果に「これは違う」と感じたら、AIチャットでその違和感を深掘りしてください。</p></div><div style="background:#f0fff4;border-radius:8px;padding:20px 24px;margin-bottom:32px"><p style="font-size:13px;font-weight:bold;color:#16a34a;margin:0 0 8px">② 戦略アクションフェーズ</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">固めた戦略をぶらさずに、Webサイト改善・営業・採用・補助金申請など、さまざまな施策に展開します。</p></div><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">さっそく分析を始める →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendWelcomeEmailAgency({ email, name }) {
  return sendEmail(email, '毎月20万円〜の伴走支援が提供できます', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、ありがとうございます。クライアント提供でご登録いただきました。</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">戦略大臣によって戦略を立案し、この戦略にもとづいたマーケティング支援を提供することで、<strong>毎月20万円〜の伴走支援サービス</strong>を提供できます。</p><hr style="border:none;border-top:1px solid #e5e5e0;margin:32px 0"><p style="font-size:15px;font-weight:bold;color:#1a1a14;margin-bottom:20px">あなたがクライアントに提供できること：</p><div style="background:#f0f4ff;border-radius:8px;padding:20px 24px;margin-bottom:16px"><p style="font-size:13px;font-weight:bold;color:#1a6fd4;margin:0 0 8px">① 戦略策定フェーズ</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">クライアントのWebサイトをAB3C分析し、「選ばれる理由」を言語化します。出てきたレポートがそのまま提案書になります。</p></div><div style="background:#f0fff4;border-radius:8px;padding:20px 24px;margin-bottom:32px"><p style="font-size:13px;font-weight:bold;color:#16a34a;margin:0 0 8px">② 戦略アクションフェーズ</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">固めた戦略をぶらさずに、Web改善・営業・採用・補助金申請など、あらゆる施策に展開します。毎月AIチャットでクライアントの経営相談に伴走することで、継続契約が自然に生まれます。</p></div><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin-bottom:24px">あなた自身のサイト、またはクライアントのWebサイトURLを入力して、AB3C分析を実行してください。レポートを見れば、提案のイメージが一気につかめます。</p><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">さっそく分析してみる →</a><p style="font-size:14px;color:#78716c;margin-top:32px;line-height:1.8;border-top:1px solid #e5e5e0;padding-top:24px">次回のメールでは「クライアントへの具体的な提案の仕方」をお伝えします。</p><p style="font-size:12px;color:#78716c">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendAnalysisCompleteEmail({ email, name }) {
  return sendEmail(email, '【戦略大臣】分析が完了しました。次のステップへ', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、AB3C分析が完了しました。</p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0 0 12px">分析結果を活用する3つの方法</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 8px">① AIチャットで「競合との違い」をさらに深掘りする</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 8px">② Webサイト改善レポートを生成して具体的な改善点を確認する</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">③ シェアURLを発行して社内・クライアントと共有する</p></div><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">分析結果を見る →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendFollowUpEmail({ email, name }) {
  return sendEmail(email, 'レポートを、誰かに見せてみましょう。', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、分析レポートはもうご覧になりましたか？</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">レポートを見て「なるほど」と思ったなら、次の一歩はシンプルです。<strong>誰かに見せてください。</strong></p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0 0 12px">2つの方法で簡単に共有できます：</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 12px"><strong>① シェアURLを発行する</strong><br>分析結果画面の「シェアする」ボタンを押すだけ。相手はログイン不要で閲覧できます。</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0"><strong>② PDFで保存する</strong><br>ブラウザの印刷機能から「PDFとして保存」を選ぶだけです。</p></div><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">レポートを開く →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendTutorial2Email({ email, name }) {
  return sendEmail(email, '戦略を固めて、安心していませんか？', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん</p><p style="font-size:16px;line-height:1.8;color:#1a1a14">分析レポートができて「よし、戦略が固まった」と安心していませんか？実は、分析はスタート地点です。</p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0 0 12px">AIチャットを開いて、今週あなたが予定しているアクションを伝えてください。</p><p style="font-size:14px;line-height:1.8;color:#1a6fd4;margin:0 0 4px">「今週、新しい取引先に営業メールを送る予定です」</p><p style="font-size:14px;line-height:1.8;color:#1a6fd4;margin:0 0 4px">「来週、採用の求人票を更新しようと思っています」</p><p style="font-size:14px;line-height:1.8;color:#1a6fd4;margin:0 0 16px">「今月中にWebサイトのトップページを修正したいです」</p><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0">そして、こう質問してください。<br>「この中で、戦略を反映させられるアクションはありますか？」</p></div><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">チャットを開く →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendTutorial3Email({ email, name }) {
  return sendEmail(email, 'レポートから、営業資料を10分で作る方法', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、シェアURLを使うと営業資料や提案書が10分で作れます。<strong>Google NotebookLMを使った方法です。</strong></p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 8px">① NotebookLM（notebooklm.google.com）を開く</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 8px">② 「新しいノートブック」を作成</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 8px">③ 「ウェブサイトを追加」にシェアURLを貼り付ける</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">④ 「スライドを作成して」と指示する</p></div><p style="font-size:16px;line-height:1.8;color:#1a1a14">AB3Cの分析内容をベースにしたスライドが自動で生成されます。そのままクライアントへの提案書として使えます。</p><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">シェアURLを発行する →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendTutorial4Email({ email, name }) {
  return sendEmail(email, '補助金申請に、戦略大臣を使う方法', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、AB3C分析のレポートは補助金申請にそのまま活用できます。</p><div style="background:#f5f2eb;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:14px;font-weight:bold;color:#1a1a14;margin:0 0 12px">手順はこの通りです：</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 12px"><strong>① 申請したい補助金の募集要項を確認する</strong><br>事業計画書や事業内容を記載する添付資料があるはずです。その資料をダウンロードしてください。（ファイルに書き込むのではなく、システムに直接書き込む形式もあります。）</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0 0 12px"><strong>② 資料の記載項目をAIチャットに読み込ませる</strong><br>記載項目や設問をコピーしてチャットに貼り付けてください。</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0"><strong>③ こう質問する</strong><br>「この項目に沿って、AB3Cの分析結果をもとに事業計画書の文章を書いてください」</p></div><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">チャットを開く →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}

export async function sendTutorial5Email({ email, name }) {
  return sendEmail(email, '毎朝5分、戦略大臣と話す習慣を作りましょう。', `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:40px 20px"><div style="font-size:24px;font-weight:bold;margin-bottom:24px;color:#1a1a14">戦略大臣</div><p style="font-size:16px;line-height:1.8;color:#1a1a14">${name||'お客様'}さん、ご登録から約1ヶ月が経ちました。一つ、新しい習慣を提案させてください。</p><div style="background:#f0f4ff;border-radius:8px;padding:20px 24px;margin:28px 0"><p style="font-size:16px;font-weight:bold;color:#1a6fd4;margin:0 0 12px">毎朝5分、その日やることをチャットに話しかけてください。</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;font-style:italic;margin:0 0 8px">「今日の午後、新規クライアントに初回提案をします」</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;font-style:italic;margin:0 0 8px">「今週中に採用ページを更新する予定です」</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;font-style:italic;margin:0 0 16px">「今月中にWebサイトのトップページを修正したいです」</p><p style="font-size:14px;line-height:1.8;color:#1a1a14;margin:0">それだけで、戦略大臣が「その取り組みに戦略をどう反映させるか」を一緒に考えてくれます。</p></div><p style="font-size:16px;line-height:1.8;color:#1a1a14">明日の朝、まず一つ話しかけてみてください。</p><a href="https://analyzer.ab3c.jp" style="display:inline-block;background:#1a6fd4;color:#fff;text-decoration:none;padding:14px 32px;border-radius:4px;font-size:15px;font-weight:bold">チャットを開く →</a><p style="font-size:12px;color:#78716c;margin-top:40px">一般社団法人デジタル経営革新協会</p></div>`);
}
